close all;
clear all;

%% Setup. User-defined File locations:
%Set the initial cell configuration
ICC = 1;

%% Setup. User-defined inputs:

%Set the number of subpopulations.
no_subpops = 2;

%Set the number of spatio-temporal point patterns generated by the 
%stochastic point process (SPP), and the number of snapshots per spatio- 
%temporal point pattern. 
no_runs=100;
no_timepoints=150;

%Set the spatial domain. 
x_max_coord=1000;
y_max_coord=1000;

% Set the bin-size (in one direction).
bin_size=10;

%Define the time steps at which the second order cumulant u2 will be 
%calculated. (Currently set to the first, middle and final time step).
u2_start_time=1;
u2_mid_time=ceil(no_timepoints/2);
u2_end_time=no_timepoints;
u2_tps = [u2_start_time u2_mid_time u2_end_time];

%% Further Setup that automatically follows the above user-definitions
%  (does not need editing).

% Location of input and output data files
parentDirectory = fileparts(cd);
grandparentDirectory = fileparts(parentDirectory);


%Generate the possible subpoulation pair-combinations
[spi,spj] = meshgrid(1:no_subpops, 1:no_subpops);
sp_combis = sort([spi(:) spj(:)],2);
sp_combis = unique(sp_combis(:,1:2),'rows');

%Define spatial domain constants
no_bins_xdir = x_max_coord/bin_size; 
no_bins_ydir = y_max_coord/bin_size;          
temp_sep_bins=0:1:floor((x_max_coord/2)/bin_size);
no_rbins= length(temp_sep_bins);
dist=0:1:no_rbins-1;


%% Generate cumulant data from point pattern data.
%We loop through twice: once for SPP-generated data with MFPM-informed doses, 
%once for SPP-generated data with STCM-informed doses.
for j = 1:2

    if(j==1)
        input_folder_name = append(grandparentDirectory,'/snapshots/v',int2str(ICC),'_dMFPM/run');
        output_folder_name = append(parentDirectory,'/v',int2str(ICC),'/mfpm_drug_time_200_to_350/');
    else
        input_folder_name = append(grandparentDirectory,'/snapshots/v',int2str(ICC),'_dSCM/run');
        output_folder_name = append(parentDirectory,'/v',int2str(ICC),'/scm_drug_time_200_to_350/');
    end

    % Load point pattern data and create snapshot-scatterplots.
    [u1_data,u2_data] = calculateCumulants_and_plotSnapshots(...
        no_subpops, sp_combis, no_timepoints, u2_tps, bin_size, ...
        no_runs, no_rbins, x_max_coord, y_max_coord, input_folder_name);
      
    % Write single-track data
    if(j==1)
        writematrix(u1_data(:,:,1),append(output_folder_name,'u1_tracks_1_MFPMdrug.csv'))
        writematrix(u1_data(:,:,2),append(output_folder_name,'u1_tracks_2_MFPMdrug.csv'))
    else
        writematrix(u1_data(:,:,1),append(output_folder_name,'u1_tracks_1_SCMdrug.csv'))
        writematrix(u1_data(:,:,2),append(output_folder_name,'u1_tracks_2_SCMdrug.csv'))
  
    end
end

